name: Update Hayase

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  check-and-update:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest Hayase release
        id: release
        run: |
          CURRENT_VERSION=$(grep 'version' Casks/hayase.rb | sed -E 's/.*version "([^"]+)".*/\1/')
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/hayase-app/ui/tags" | jq -r '.[0].name')
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/hayase-app/ui/releases/tags/$LATEST_VERSION | jq -r '.assets[]? | select(.name == "mac-hayase-'"${LATEST_VERSION#v}"'-mac.dmg") | .browser_download_url')

          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"
          echo "Download URL: $DOWNLOAD_URL"

      - name: Check if update is needed
        id: check
        run: |
          if [ "${{ steps.release.outputs.latest_version }}" != "${{ steps.release.outputs.current_version }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "Update needed: ${{ steps.release.outputs.current_version }} -> ${{ steps.release.outputs.latest_version }}"
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
            echo "No update needed"
          fi

      - name: Download and calculate SHA256
        if: steps.check.outputs.update_needed == 'true'
        id: sha256
        run: |
          # Download the DMG and calculate SHA256
          curl -sL "${{ steps.release.outputs.download_url }}" -o hayase.dmg
          SHA256=$(shasum -a 256 hayase.dmg | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "SHA256: $SHA256"
          rm hayase.dmg

      - name: Update Cask file
        if: steps.check.outputs.update_needed == 'true'
        run: |
          # Update version
          sed -i '' 's/version "[^"]*"/version "${{ steps.release.outputs.latest_version }}"/' Casks/hayase.rb

          # Update SHA256
          sed -i '' 's/sha256 "[^"]*"/sha256 "${{ steps.sha256.outputs.sha256 }}"/' Casks/hayase.rb

      - name: Test the updated Cask
        if: steps.check.outputs.update_needed == 'true'
        run: |
          # Add this tap and test the Cask
          brew tap ${{ github.repository }}
          brew install --cask --dry-run hayase

      - uses: fregante/setup-git-user@v2
        if: steps.check.outputs.update_needed == 'true'

      - name: Commit and push changes
        if: steps.check.outputs.update_needed == 'true'
        run: |
          git add Casks/hayase.rb
          git commit -m "chore: update Hayase to v${{ steps.release.outputs.latest_version }}"
          git push
